apiVersion: v1
kind: Secret
metadata:
  name: wingman-secrets
  labels:
    app: wingman
type: Opaque
stringData:
  cf-api-token: "{{ .Values.secrets.cfApiToken | default "" }}"
  npm-password: "{{ .Values.secrets.npmPassword | default "" }}"
  unifi-password: "{{ .Values.secrets.unifiPassword | default "" }}"
  ptero-api-key: "{{ .Values.secrets.pteroApiKey | default "" }}"
  flask-secret-key: "{{ .Values.secrets.flaskSecretKey | default (randAlphaNum 32) }}"
